# Autogenerated wrapper script for Wigxjpf_jll for armv6l-linux-musleabihf
export libwigxjpf, libwigxjpf_quadmath

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Wigxjpf")
JLLWrappers.@declare_library_product(libwigxjpf, "libwigxjpf_shared.so")
JLLWrappers.@declare_library_product(libwigxjpf_quadmath, "libwigxjpf_quadmath_shared.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libwigxjpf,
        "lib/libwigxjpf_shared.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwigxjpf_quadmath,
        "lib/libwigxjpf_quadmath_shared.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
