# Autogenerated wrapper script for Wigxjpf_jll for i686-linux-gnu
export wigxjpf

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Wigxjpf")
JLLWrappers.@declare_library_product(wigxjpf, "libwigxjpf_shared.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        wigxjpf,
        "lib/libwigxjpf_shared.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
