# Autogenerated wrapper script for Wigxjpf_jll for x86_64-w64-mingw32
export libwigxjpf, libwigxjpf_quadmath

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Wigxjpf")
JLLWrappers.@declare_library_product(libwigxjpf, "libwigxjpf_shared.dll")
JLLWrappers.@declare_library_product(libwigxjpf_quadmath, "libwigxjpf_quadmath_shared.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libwigxjpf,
        "bin\\libwigxjpf_shared.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwigxjpf_quadmath,
        "bin\\libwigxjpf_quadmath_shared.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
